apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: "avro-connector"
  namespace: "kafka"
  labels:
    strimzi.io/cluster:
      avro-connect-cluster
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  config:
    connector.class: io.confluent.connect.s3.S3SinkConnector
    task.max: '1'
    topics: nyc-avro-topic
    s3.region: us-east-1
    s3.bucket.name: openlake-tmp
    s3.part.size: '5242880'
    flush.size: '10000'
    topics.dir: nyc-taxis-avro
    timezone: UTC
    store.url: https://play.min.io:50000
    storage.class: io.confluent.connect.s3.storage.S3Storage
    format.class: io.confluent.connect.s3.format.parquet.ParquetFormat
    partitioner.class: io.confluent.connect.storage.partitioner.DefaultPartitioner
    s3.credentials.provider.class: com.amazonaws.auth.DefaultAWSCredentialsProviderChain
    behavior.on.null.values: ignore
    auto.register.schemas: false
    parquet.codec: snappy
    schema.registry.url: http://kafka-schema-registry-cp-schema-registry:8081
    value.converter: io.confluent.connect.avro.AvroConverter
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter.schema.registry.url: http://kafka-schema-registry-cp-schema-registry:8081
