apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: sparkjob-magic-test-2
  namespace: spark-operator
spec:
  # schedule: "@every 1h"
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "registry.min.dev/sparkjob"
  imagePullPolicy: Always
  mainApplicationFile: local:///app/main-magic.py
  sparkVersion: "3.3.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 3
    # coreLimit: "1200m"
    memory: "2048m"
    labels:
      version: 3.3.1
    serviceAccount: my-release-spark
    env:
      - name: AWS_REGION
        value: us-east-1
      - name: AWS_ACCESS_KEY_ID
        value: kserver
      - name: AWS_SECRET_ACCESS_KEY
        value: kserver123
  executor:
    cores: 1
    instances: 3
    memory: "1024m"
    labels:
      version: 3.3.1
    env:
      - name: AWS_REGION
        value: us-east-1
      - name: AWS_ACCESS_KEY_ID
        value: kserver
      - name: AWS_SECRET_ACCESS_KEY
        value: kserver123
